### ISSUE TITLE
Add `AgreementPage` back

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#126]
- If VC required by the offering selected doesn't exist in `vcProvider`, then...
  - show `AgreementPage` as part of a **full screen modal** which begins the KCC flow
  - get the terms of service string (comes from pfi) in a `useEffect()`
  - on complete, continue to the `PfiVerificationPage`

**Comment by diehuxx** [comment]
Wire frame draft.

![Screenshot 2024-04-25 at 10 09 18 AM](https://github.com/TBD54566975/didpay/assets/74206001/5c4e2c96-3fea-42b5-aae9-252b06483de2)

**Comment by diehuxx** [comment]
Notes: In `Payin/PayoutDetailsPage`, go to the `AgreementPage`. Then use a `useEffect` to check for `vcProvider`.
