### ISSUE TITLE
Should didpay also be a web app (from flutter)

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/didpay#26]
It is possible theoretically to run this as a web app (PWA even). 

`flutter create --platforms web .`

Will create it as a web app and 

`flutter run -d chrome` to test it out. 

This may be of interest to avoid the barrier for some to install the app the first time (or places where the app store isnt' available). 
To do this the main things are: 

* don't use `dart:io`
* don't use webview (there are other ways on the web)

But mostly things can work (as to how people could migrate from web storage to native storage - that is another matter). 

Worth consideration?

**Comment by ethan-tbd** [comment]
definitely worth consideration! personally, i'd love to make the mobile version of didpay the "star of the show" and have the web app (and maybe PWA) version be somewhat simpler. i say this because mobile-first behavior would allow us to focus on making didpay (and thus tbDEX) associated with quick, on-the-go transactions. not to mention push notifications and consistent ui/ux are better associated with mobile experiences!

**Comment by ethan-tbd** [comment]
@wesbillman @mistermoe any additional thoughts?

**Comment by michaelneale** [comment]
yeah a webapp would have less persistence and power (at least PWAs are for the forseeable future) but very useful. not sure if that is the job of the flutter app to provide or a seperate simply web/PWA experience for some subset of functionality.

**Comment by wesbillman** [comment]
I think it's great. The downside is that it's not super "webby" like the layouts and accessibility/navigation stuff can get a bit weird. I like we should prototype it to get some thoughts from others though. In the past I've keep the web and mobile stuff separate for this reason, but maybe it's time for that to change :)

Also, even if we make this a web app, we should be able to generate all the FTL stuff for both mobile and web, which reduces the amount of web work a bit.

**Comment by michaelneale** [comment]
yeah its fine if it is seperate I think - but I also don't mind web apps that are minimalist too (which mobile encourages, and this one would be) as long as it isn't "trying too hard" and feels too weird on the web. 

What do you mean "generate the FTL stuff"?

**Comment by michaelneale** [comment]
@ethan-tbd did this end up being done - or we decided not to?

**Comment by ethan-tbd** [comment]
yea, we decided to re-introduce the `web` folder to allow didpay to be a web app in [this pr](https://github.com/TBD54566975/didpay/pull/102) (but won't be a priority as we want to focus on the mobile experience)
