### ISSUE TITLE
Update `SendPage` to remove "Verifying DAP..." loading message 

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#285]
- similar to what was achieved in https://github.com/TBD54566975/didpay/pull/281, we want to consolidate any consecutive loading spinners into one loading page
- currently, you can go to `SendPage` via the send tab in the bottom navigation bar. from here, typing in a dap (e.g. `@moegrammer/didpay.me`) and hitting the next button triggers a "Verifying DAP..." loading message followed by a "Fetching offerings..." loading message which means you have entered the payment flow starting at `PaymentAmountPage`
- the goal of this issue is to remove the "Verifying DAP..." loading message in `SendPage` and instead put a small loading spinner to the right of the DAP input form when resolving the DAP 
  - old flow: input DAP -> hit next -> see "Verifying DAP..." -> see "Fetching offerings..." -> enter `PaymentAmountPage`
  - new flow: input DAP -> hit next -> see small loading spinner next to DAP input form  -> see "Fetching offerings..." -> enter `PaymentAmountPage`

**Comment by victoreronmosele** [comment]
.take

**Comment by victoreronmosele** [comment]
Hi @ethan-tbd,  I made a [PR](305) implementing this.
