### ISSUE TITLE
Create UI tests for `AccountBalanceCard` widget

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#286]
- using the existing test suite as an example, create UI tests to stress-test the `AccountBalanceCard` widget 
- currently, the `AccountBalanceCard` widget is only responsible for displaying the account total and account currency which is fetched from the `AccountBalanceNotifier`

**Comment by victoreronmosele** [comment]
.take

**Comment by victoreronmosele** [comment]
@blackgirlbytes, hi! 

The issue is going well, thanks.

I plan to create a PR very soon.

**Comment by victoreronmosele** [comment]
The [PR](https://github.com/TBD54566975/didpay/pull/311) is up now.

**Comment by blackgirlbytes** [comment]
ah, thank you! We'll have @ethan-tbd check this when he gets a chance! Appreciate the contribution @victoreronmosele
