### ISSUE TITLE
Create UI tests for `CurrencyDropdown` widget

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#287]
- using the existing test suite as an example, create UI tests to stress-test the `CurrencyDropdown` widget
- the` CurrencyDropdown` widget is responsible for:
  - reading the passed in `PaymentAmountState` to render a list of PFI offerings to choose from
  - updating the passed in `PaymentAmountState` when a new offering is selected from the "Select currency" modal

**Comment by mohitrajsinha** [comment]
.take

**Comment by mohitrajsinha** [comment]
Hey @ethan-tbd , I’ve created a few tests, but I’m running into an issue with the second one—it keeps failing. Do you have any suggestions on how I might resolve this?

Here’s the commit link with the code: [Commit 149c5b22e57b481c21d66da96c90c3ad6f6f5591](https://github.com/mohitrajsinha/didpay/commit/149c5b22e57b481c21d66da96c90c3ad6f6f5591)

Thanks for any insights you can provide!

**Comment by blackgirlbytes** [comment]
Hey @mohitrajsinha maybe it would help if you open a PR? That way ethan or me could check it out and suggest changes to help you get your test working!

**Comment by ethan-tbd** [comment]
@mohitrajsinha there are two problems that are contributing to the failing test case: 
1.  follow the structure of the existing test suite by using `WidgetHelpers.testableWidget()` (this will take care of the localized string errors)
2. if you take a look at `ModalSelectCurrency`, you will see that if `offeringsMap` in `PaymentAmountState` is null, then an empty container is rendered. in your `setUp` function, make sure to initialize `offeringsMap` (hint: look at the `TestData` class).

**Comment by ethan-tbd** [comment]
@mohitrajsinha also some nits:
1. make sure the name of the test file ends in `_test`
2. instead of using `find.byKey()`, you can just use `find.text('USD')` since you are setting the `testCurrency` value to `USD`

**Comment by mohitrajsinha** [comment]
Yeah ,it was great to work on this issue. It was my first time working on a flutter tests. 

Thanks for your suggestions.
