### ISSUE TITLE
Create UI tests for `DapForm` widget

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#288]
- using the existing test suite as an example, create UI tests to stress-test the `DapForm` widget
- the `DapForm` widget is responsible for:
  - accept user input and parse / resolving that input into a valid DAP
  - updating the passed in `AsyncValue<Dap>` when a DAP is entered to let the `SendPage` know when it should render a loading spinner or push to the `PaymentAmountPage`

**Comment by victoreronmosele** [comment]
.take
