### ISSUE TITLE
Create tests for `TbdexOrderInstructionsNotifier`

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#294]
- using the existing test suite as an example, create tests to stress-test `TbdexOrderInstructionsNotifier`
- the `TbdexOrderInstructionsNotifier` widget is responsible for:
  - polling a specific PFI for a specific exchange id and looking for a tbDEX `OrderInstructions` message with exponential backoff retries

**Comment by victoreronmosele** [comment]
.take
