### ISSUE TITLE
Fix flutter web crash

### ISSUE THREAD

**Issue by ethan-tbd** [TBD54566975/didpay#297]
Currently, running didpay using flutter web results in the following error:
```
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
```

Fix the error by adding the `flutter_inappwebview_web` package and editing `web/index.html` (hint: follow the thread here https://github.com/pichillilorenzo/flutter_inappwebview/issues/1468)

**Comment by victoreronmosele** [comment]
.take

**Comment by victoreronmosele** [comment]
This crash no longer occurs after https://github.com/TBD54566975/didpay/pull/304. 

The web app now loads without a crash. 

<img width="75%" alt="Screenshot of the DIDPay app after loading successfully" src="https://github.com/user-attachments/assets/78ea0cb2-c8da-4a7d-9491-58537e450ba0">

**Comment by ethan-tbd** [comment]
@victoreronmosele you're right, looks like the error detailed in this issue was fixed by updating `flutter_inappwebview` [here](https://github.com/TBD54566975/didpay/pull/301/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25). will close out this issue
